### ISSUE TITLE
Crash on Fedora 22 Workstation x64

### ISSUE THREAD

**Issue by ghost** [muflone/remmina-plugin-url#1]
Compiled and installed the plugin. When creating a new connection and selecting the plugin in the combo box remmina crashes immediately. Any clues to what I'm doing wrong?

**Comment by muflone** [comment]
What version of Remmina are you using?

**Comment by ghost** [comment]
1.2.0-rcgit.3

**Comment by muflone** [comment]
This issue was fixed with the new version 1.2, compatible with remmina 1.2 and higher
